root: true
parser: vue-eslint-parser
parserOptions:
  ecmaFeatures: { jsx: true }
  ecmaVersion: 2020
  parser: '@typescript-eslint/parser'
  sourceType: module
extends:
  - 'airbnb-base'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:vue/recommended'
env:
  browser: true
rules:
  "@typescript-eslint/explicit-module-boundary-types": 0
  "@typescript-eslint/no-explicit-any": 0
  arrow-parens: 0
  import/extensions: 0
  import/no-extraneous-dependencies: ["error", {"devDependencies": ["src/stories/**"]}]
  import/no-unresolved: 0
  max-len: ["error", { "code": 120 }]
  no-alert: 0
  no-bitwise: 0
  no-console: ["warn", { allow: ["info", "warn", "error", "debug"] }]
  no-extra-semi: 2
  no-mixed-operators: 0
  no-param-reassign: 0
  no-plusplus: 0
  no-promise-executor-return: 0
  no-return-assign: 0
  no-shadow: 0
  no-underscore-dangle: 0
  no-use-before-define: 0
  semi: 0
  vue/multi-word-component-names: 0
overrides:
  - files: ['*.vue']
    rules:
      indent: 'off'
      vue/html-indent: 0
      vue/html-self-closing: 0
      vue/max-attributes-per-line: 0
      vue/no-parsing-error: [2, { "x-invalid-end-tag": false }]
  - files: ['storybook-init-framework-entry.js']
    rules:
      import/no-extraneous-dependencies: 0
