root: true
extends:
  - 'plugin:vue/recommended'
  - 'airbnb-base'
env:
  browser: true
rules:
  arrow-parens: 0
  import/no-extraneous-dependencies: ["error", {"devDependencies": ["src/stories/**"]}]
  no-bitwise: 0
  no-extra-semi: 2
  no-mixed-operators: 0
  no-param-reassign: 0
  no-plusplus: 0
  no-return-assign: 0
  no-shadow: 0
  no-underscore-dangle: 0
  no-use-before-define: 0
  semi: 0
overrides:
  - files: ['*.vue']
    rules:
      indent: 'off'
      vue/html-indent: 0
      vue/html-self-closing: 0
      vue/max-attributes-per-line: 0
      vue/no-parsing-error: [2, { "x-invalid-end-tag": false }]
